### PR TITLE
removed typo from root folder

### PR DESCRIPTION
**Pull request by akshaysonawaneS**
#### Removed typo 
```
root_folder = exp_path = Path().absolute()..parent / "experiments" 
```
#### changed to
```
root_folder = Path().absolute().parent / "experiments" 
```

### CODE REVIEW

**Review by bowni — APPROVED** [review]
Great!

**Comment by bowni** [comment]
@natct10 or @RomainGoussault can one of you provide the 2nd approval and then merge?

**Review by RomainGoussault — APPROVED** [review]
Well done @akshaysonawaneS !

**Comment by natct10** [comment]
Awesome, thank you @akshaysonawaneS!

**Pull request merged**
