### PR TITLE
Pytest 6.2.2

### PR DESCRIPTION
**Pull request by natct10**
Pytest changelog: https://docs.pytest.org/en/stable/changelog.html

### CODE REVIEW

**Comment by arthurPignet** [comment]
Why do you rename it requirements instead of dev-req ? There already is a requirement.txt, in the mplc folder.

**Review by arthurPignet — COMMENTED** [review]
Ok for the pytest update, but I don't understand why renaming dev-req. There already exist a mplc/requirement.txt, which is enough to run mplc and dev-req is for running the test, flake it, and make a pip release

**Comment by natct10** [comment]
> Ok for the pytest update, but I don't understand why renaming dev-req. There already exist a mplc/requirement.txt, which is enough to run mplc and dev-req is for running the test, flake it, and make a pip release

Oh my bad, I got confused, I'll revert this part

**Review by arthurPignet — APPROVED** [review]

**Comment by arthurPignet** [comment]
👍

**Review by bowni — APPROVED** [review]

**Pull request merged**
