### PR TITLE
Homogenize aggregation and aggregation_weighting

### PR DESCRIPTION
**Pull request by jeromechambost**
Fix aggregation method for experiments, that stayed default "data-volume"

### CODE REVIEW

**Review by natct10 — APPROVED** [review]
Neat, thank you @jeromechambost!

**Review by bowni — APPROVED** [review]
LGTM - @arthurPignet could you please review, and merge if everything looks good to you?

**Review by arthurPignet — COMMENTED** [review]
I think that the difference between _aggregation_weighting and aggregation_weighting is not easy to understand in a first look.
I would suggest to merge those, as every Aggregator holds an attribute .name. (I think that scenario.aggregation_weighting == scenario._aggregation_weighting.name.

Then we can copy the operation done by corruption, or mpl for the initialization. the parameter aggregation_weighting could be either an aggregator instance, or a string identifier

**Comment by arthurPignet** [comment]
I merged it because I am going to work on aggregators in the PR315

**Pull request merged**
